#-------------------------------
# General Site Settings

title: 번역봇
logo: 
author: themefisher
description: this is meta description
email: msck_korea@kakao.com, leonardo210328@gmail.com
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: Invite, link: 'https://discord.com/oauth2/authorize?client_id=825607802919321640&permissions=8&scope=applications.commands%20bot'}
- {name: Support, link: 'https://discord.gg/KM7SJkXN9n'}
- {name: 번역봇 명령어, link: '/commands'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: 안녕하세요! 디스코드 봇 번역봇 사이트 입니다!

social:
- {icon: "ti-Discord", link: "https://discord.gg/KM7SJkXN9n"}
- {icon: "ti-instagram", link: "https://www.instagram.com/discord_translation/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  번역봇이란, 디스코드 봇을 말하며 현재 서버수는 대략 190서버이고, 기능은 번역, 노래, 주식, 도박, 롤전적, 배틀그라운드전적, 투표, eval, 말하기 등을 가졌습니다.
blurb-btn-link: 'https://discord.com/oauth2/authorize?client_id=825607802919321640&permissions=8&scope=applications.commands%20bot'
blurb-btn-name: 내 서버에 번역봇 초대하기


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: 번역봇
skills:
- {name: Python, color: '#fdb157', value: '100%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: People's help, color: '#bdecf6', value: '40%'}
- {name: VScode, color: '#ffbcaa', value: '30%'}


#-------------------------------
# Exprerience Section

experience-title: 번역봇 성장
experience:
- {name: 번역봇 최초 등록, icon: 'icon-1.png', date: 'Mar 2021 -  Present', organization: 'Discord'}
- {name: 번역봇 한디리, icon: 'icon-2.png', date: 'Mar 2021 -  Present', organization: 'koreanbots.dev'}
- {name: UI디자인, icon: 'icon-3.png', date: 'Apr 2021 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: 업적
education:
- {name: 번역봇 봇 개설, date: '2021', organization: '번역봇을 최초로 3월 28일에 개설을 하였습니다.'}
- {name: 한국 디스코드 봇 리스트 봇 추가, date: '2021', organization: '번역봇을 한디리에 4월1일에 추가했습니다.'}
- {name: 디스코드 verifycation, date: '2021', organization: '2021/4/27 에 디스코드 공식 인증을 받았습니다.'}



#-------------------------------
# Services Section

services-title: 번역봇 명령어
services:
- {
    name: ㅂ도움말,
    description: '번역봇에 대한 명령어 도움말이 나옵니다.',
    active: # Add true to select section
  }
- {
    name: ㅂ내정보,
    description: '자신의 디스코드 정보를 불러옵니다.',
    active: # Add true to select section
  }  
- {
    name: 번역아, 번역아 뭐해,
    description: '번역봇이랑 이야기를 나눌수 있습니다.',
    active: # Add true to select section
  }
- {
    name: ㅂ초대링크,
    description: '번역봇의 초대링크를 얻을수 있습니다..',
    active: # Add true to select section
  }  
- {
    name: ㅂ지원서버,
    description: '번역봇의 서포트서버가 나옵니다.',
    active: # Add true to select section
  }
- {
    name: ㅂ로고,
    description: '번역봇의 로고가 나옵니다..',
    active: # Add true to select section
  }  
- {
    name: ㅂ타이머,
    description: 'ㅂ타이머 n 을 하시면 타이머가 시작됩니다.(n은 초단위입니다.)',
    active: # Add true to select section
  }
- {
    name: ㅂ사연,
    description: 'ㅂ사연 할말 을 하시면 번역봇의 서포트에 사연이 전송됩니다.',
    active: # Add true to select section
  }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"

  - image : "assets/images/portfolio/item-2.png"
    url: "#"

  - image : "assets/images/portfolio/item-3.png"
    url: "#"
